### PR TITLE
Accurate probability (act 2)

### PR DESCRIPTION
**Pull request by peter50216**

### CODE REVIEW

**Comment by peter50216** [comment]
Verified that all data on my hand works with FUDGE_FACTOR=0, and the probability looks sane.

**Comment by peter50216** [comment]
Also the version with FUDGE_FACTOR = 0 and this commit is at my fork: https://peter50216.github.io/ac-nh-turnip-prices/ if anyone want to try it.

Please let me know if there's any issue / weird probability generated.

**Comment by ZZZZzzzzac** [comment]
try Sunday 100 and MonAM 85 and you will find pattern 3 has 10%+ probability for each subpattern

i don't quite understand you algorithm, could you please explain and give a toy example?

**Comment by peter50216** [comment]
> try Sunday 100 and MonAM 85 and you will find pattern 3 has 10%+ probability for each subpattern
> and total probability of pattern 3 > 90%
> i don't quite understand your algorithm, could you please explain and give a toy example?

A toy example is as in the example in #95. Detail calculation there and the result of decreasing / 94 / 83 matches it.

**Comment by ZZZZzzzzac** [comment]
> > try Sunday 100 and MonAM 85 and you will find pattern 3 has 10%+ probability for each subpattern
> > and total probability of pattern 3 > 90%
> > i don't quite understand your algorithm, could you please explain and give a toy example?
> 
> A toy example is as in the example in #95. Detail calculation there and the result of decreasing / 94 / 83 matches it.
> 
> Also in the case 100 / 85, a low probability for pattern 1 / 2 sounds reasonable to me, since both of them has `intceil(randfloat(0.85, 0.9) * 100)` as first price, for which is really hard to get `85` since that means the randfloat() result has to lie in the range [0.85, 0.8500001].

try 86, the same, it's not the randfloat problem

**Comment by peter50216** [comment]
> > > try Sunday 100 and MonAM 85 and you will find pattern 3 has 10%+ probability for each subpattern
> > > and total probability of pattern 3 > 90%
> > > i don't quite understand your algorithm, could you please explain and give a toy example?
> > 
> > 
> > A toy example is as in the example in #95. Detail calculation there and the result of decreasing / 94 / 83 matches it.
> > Also in the case 100 / 85, a low probability for pattern 1 / 2 sounds reasonable to me, since both of them has `intceil(randfloat(0.85, 0.9) * 100)` as first price, for which is really hard to get `85` since that means the randfloat() result has to lie in the range [0.85, 0.8500001].
> 
> try 86, the same, it's not the randfloat problem

For 86, pattern 3 is less possible because it has `randfloat(0.4, 0.9) * 100` for first price, which is ~20x harder to get to 86 than `randfloat(0.85, 0.9) * 100`, so the conditional probability is also 20x smaller.

**Comment by ZZZZzzzzac** [comment]
> > > > try Sunday 100 and MonAM 85 and you will find pattern 3 has 10%+ probability for each subpattern
> > > > and total probability of pattern 3 > 90%
> > > > i don't quite understand your algorithm, could you please explain and give a toy example?
> > > 
> > > 
> > > A toy example is as in the example in #95. Detail calculation there and the result of decreasing / 94 / 83 matches it.
> > > Also in the case 100 / 85, a low probability for pattern 1 / 2 sounds reasonable to me, since both of them has `intceil(randfloat(0.85, 0.9) * 100)` as first price, for which is really hard to get `85` since that means the randfloat() result has to lie in the range [0.85, 0.8500001].
> > 
> > 
> > try 86, the same, it's not the randfloat problem
> 
> For 86, pattern 3 is less possible because it has `randfloat(0.4, 0.9) * 100` for first price, which is ~20x harder to get to 86 than `randfloat(0.85, 0.9) * 100`, so the conditional probability is also 20x smaller.

it's my misread the result, examining other pattern

**Comment by ZZZZzzzzac** [comment]
check multiple patterns and seems good, besides some precision error <0.01%

**Pull request merged**
