### PR TITLE
add alert message upon invalid inputs

### PR DESCRIPTION
**Pull request by John-Kryspin**
Solves #386
image

### CODE REVIEW

**Comment by Lego6245** [comment]
Not the hugest fan of `alert` here. Maybe a treatment that shows a proper error in the output box instead?

**Comment by John-Kryspin** [comment]
Yeah, that would work as well, but I thought it would be good to really blast this message into the user, as I worry if its in the output box the user might keep typing in more prices and see that message too late.

**Comment by peter50216** [comment]
FYI, there's a similar PR at #349

**Comment by theRTC204** [comment]
I appreciate your desire to contribute, but I have to agree with the other comments here. Use of an alert message is really not a good solution to this UX concern.

**Comment by John-Kryspin** [comment]
No problem! I appreciate everyone’s input, I’ll close this PR

**Pull request closed without merging**
