### PR TITLE
Contributors Section At Bottom of Page

### PR DESCRIPTION
**Pull request by Trevor-Welch**
I went ahead and added everyone on https://github.com/mikebryant/ac-nh-turnip-prices/graphs/contributors and their respective GitHub page as the link.

### CODE REVIEW

**Comment by Trevor-Welch** [comment]
Also, I have no idea why my commits are just now coming in, this PR was based on the Master branch after PR #67

**Comment by peter50216** [comment]
Are you sending the wrong branch for pull request? The "Files changed" looks completely unrelated to the PR title and only have some unrelated changes.

**Comment by Trevor-Welch** [comment]
It is fixed now. I also was very confused by "100+ lines changed" for a very small edit!

**Comment by theRTC204** [comment]
I don't fully understand why I don't show up as a contributor, but oh well!

**Comment by theRTC204** [comment]
I would consider using this endpoint to make a real-time fetch to the repo to get the contributors list. It sucks that it will forever not include some people (like me!) but this will make it so we don't have to constantly update the list every time someone contributes.

https://api.github.com/repos/mikebryant/ac-nh-turnip-prices/contributors

**Comment by mikebryant** [comment]
@theRTC204 It looks like it does include everyone - the API matches up with `git log` - it's not caring where commits came from as far as I can tell

```
m@lt:~/go/src/github.com/mikebryant/ac-nh-turnip-prices$ git log | grep Ryan
Author: Ryan Carbotte <ryan@boldcommerce.com>
Author: Ryan Carbotte <ryan@boldcommerce.com>
Author: Ryan Carbotte <ryan@boldcommerce.com>
Author: Ryan Carbotte <ryan@boldcommerce.com>
```

```
$ curl https://api.github.com/repos/mikebryant/ac-nh-turnip-prices/contributors | jq '.[1]'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11715  100 11715    0     0  38159      0 --:--:-- --:--:-- --:--:-- 38159
{
  "login": "theRTC204",
  "id": 6956413,
  "node_id": "MDQ6VXNlcjY5NTY0MTM=",
  "avatar_url": "https://avatars0.githubusercontent.com/u/6956413?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/theRTC204",
  "html_url": "https://github.com/theRTC204",
  "followers_url": "https://api.github.com/users/theRTC204/followers",
  "following_url": "https://api.github.com/users/theRTC204/following{/other_user}",
  "gists_url": "https://api.github.com/users/theRTC204/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/theRTC204/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/theRTC204/subscriptions",
  "organizations_url": "https://api.github.com/users/theRTC204/orgs",
  "repos_url": "https://api.github.com/users/theRTC204/repos",
  "events_url": "https://api.github.com/users/theRTC204/events{/privacy}",
  "received_events_url": "https://api.github.com/users/theRTC204/received_events",
  "type": "User",
  "site_admin": false,
  "contributions": 4
}
```

**Comment by mikebryant** [comment]
Closing in favour of #84

**Comment by theRTC204** [comment]
Oh, yeah I figured out a way to link my commits to the project. I misunderstood the docs, and the problem actually was my email address after all.

**Pull request closed without merging**
