### PR TITLE
Sort row output by probability

### LINKED ISSUE #65: [Feature Proposal] Sort output rows by probability, and keep the "All patterns" row at the top.
Reading the output table could be more intuitive if the rows were sorted by their probability, so that the most likely outcome is the first one that the user sees.

It would also be nice keep the "All patterns" row at the top of the table as a summary.

If either of these changes sound good, I'd be happy to make a pull request referencing this issue that implements them.

Here's a side-by-side of the current and proposed behavior:
current_behavior

proposed_change

### PR DESCRIPTION
**Pull request by ChiefMilesEdgeworth**
[x] Sorts output by probability in descending order
[x] Sets the "All patterns" case at the top

Closes #65 

Let me know if there's anything that needs done! :)

### CODE REVIEW

**Comment by theRTC204** [comment]
After thinking further on this, sorting by probability could be misleading. Given the probabilities are currently on a per-row basis, the more possible matches there are for one pattern, the lower it's individual row probability will be.

I think this change needs more thought before introduction.

**Comment by ChiefMilesEdgeworth** [comment]
I wonder if it would be possible to have all the rows that share a probability showing just one large block probability

**Comment by ChiefMilesEdgeworth** [comment]
I could see if I could do something like that

**Comment by theRTC204** [comment]
There's discussion around overall % chance happening in issue https://github.com/mikebryant/ac-nh-turnip-prices/issues/72.

**Comment by ChiefMilesEdgeworth** [comment]
I'll hold onto this until that discussion finalizes, and see if I can't sort it based on the large percentages similarly. :)

**Comment by ChiefMilesEdgeworth** [comment]
If #115 is merged, this won't be necessary anymore.

**Comment by ChiefMilesEdgeworth** [comment]
Actually, I'm just going to close this since it's probably not the behavior we want regardless.

**Pull request closed without merging**
