### PR TITLE
Added a fresh coat of paint from Materialize

### PR DESCRIPTION
**Pull request by theRTC204**
Love this little tool, and I thought it would be nice to make it a little easier on the eyes. This change adds some visual styling based on Material Design language, using the Materialize library.

image

### CODE REVIEW

**Comment by mikebryant** [comment]
damn, I keep not seeing PRs and making them conflict :p

**Comment by Trevor-Welch** [comment]
Would love to have a small Discord server for people who want to contribute to the project.

I know I want to contribute as well!

**Comment by theRTC204** [comment]
@mikebryant I ported your update into my PR and also fixed the link's name from Gitlab to Github.

**Comment by mikebryant** [comment]
Oh lulz. I'm too used to Gitlab at work - thanks for spotting that!

**Comment by mikebryant** [comment]
This PR is awesome, thank you so much :)

**Pull request merged**
