### PR TITLE
Update readme

### LINKED ISSUE #178: Text does not load when running from local filesystem
None of the text gets loaded when running from the local filesystem.

Looking at the console this seems to be the error

`Access to XMLHttpRequest at 'file:///D:/Download/ac-nh-turnip-prices-master/ac-nh-turnip-prices-master/locales/en.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

### PR DESCRIPTION
**Pull request by Lysoun**
I have added the fixes that was requested in #249, the original pull request

Closes #178

### CODE REVIEW

**Comment by Lysoun** [comment]
I could not find a way to center the picture so I removed it... If you find a way to do it using markdown, that would be appreciated.

**Comment by theRTC204** [comment]
Markdown doesn't support positioning in that way. You could leave the image in place, but it would be left aligned always.

**Comment by Lysoun** [comment]
I am pretty sure you can squash them on merge, can't you?

**Comment by theRTC204** [comment]
@Lysoun I can, but a maintainer really shouldn't have to cleanup a contribution.

**Comment by Lysoun** [comment]
But using the github squash makes it so much easier and it even properly adds the co-authors in the squash commit while I would have to ask @promarcel their email to properly push a squashed commit with the co-author. It is just two clicks away from the "merge" button in github

**Pull request merged**
