### PR TITLE
Add data visualization

### PR DESCRIPTION
**Pull request by PastisD**
I know that #11 add dataviz, but it's made on an old version :P

So I added the same graph as https://elxris.github.io/Turnip-Calculator/ on current version
The graph is based on "All patterns" probability.

image

### CODE REVIEW

**Comment by rhuwellsamano** [comment]
Yes!!

**Comment by theRTC204** [comment]
I like the idea of having some sort of data visualization, but lifting the exact code from another popular open source project, without providing reference back to the original creators, seems kind of scummy. 🤷‍♂️

**Comment by PastisD** [comment]
Indeed, I forgot to add link in footer :)

**Comment by mikebryant** [comment]
There's quite a few things I don't like about their version, so I'm afraid I won't be accepting this. Thank you for the contribution though - it's given me a poke, and I've started from scratch using Chart.js and made #104

**Comment by PastisD** [comment]
Not a problem, i wanted a chart, you made it :P

**Pull request closed without merging**
