### PR TITLE
Probability updates

### PR DESCRIPTION
**Pull request by alexwh**
Calculate and display the probability in the UI
Still needs to recalculate based on removed patterns. e.g. small spike from random is 35%, but if the only patterns in the list are random and small spike, then it should be 35/(35+20), with 20 being random's chance

### CODE REVIEW

**Comment by alexwh** [comment]
Implemented the percentage reevaluation mentioned in the first post, I think the probability maths should be correct.

**Comment by alexwh** [comment]
Phew that was a heck of a merge conflict. Will test shortly to see if everything is on fire.

**Comment by alexwh** [comment]
I believe everything is now merged/bugfixed correctly.

**Comment by mikebryant** [comment]
Thanks for this, I've got a version of this merged in master now :)

**Pull request closed without merging**
