### PR TITLE
darkmode using darkmodejs

### PR DESCRIPTION
**Pull request by Sujeom**
In reference to issue #70 

Lmk if color changes are needed or feel free to make any edits. :)

### CODE REVIEW

**Comment by Sujeom** [comment]
Made some adjustments. this is the current look. Should I go for another scheme instead of the purple/navy?
Screenshot_20200416_011112

**Comment by theRTC204** [comment]
I did see the adjustments... but I have to be honest I'm not really fond of the pallette used here. Personally I would like to see the site get a really eye catching darkmode overall.

I think I would like to get @mikebryant's opinion on this before I give it my approval.

**Comment by Sujeom** [comment]
I get what you mean. I'm not entirely sure what pallette would give the best AC vibe.

**Comment by mikebryant** [comment]
The blue/black theme is reasonable. I'm not sure what an "AC" theme would be. The note text (like "This affects your pattern") is a little hard to read for me.

**Comment by Sujeom** [comment]
Updated the coloring on the note texts.

**Pull request merged**
