### PR TITLE
Category total chance

### LINKED ISSUE #72: [Feature Proposal] Overall Percent Chance
Hello,

I was wondering if this could be an additional feature to continue with the statistic trend.

image

I made a `working sample` for the current version as of 4/12/2020. It loops through the data found in the table and adds all of the percent chances per category.

I use the `Custom JavaScript for Websites 2` extension for Chrome to run outside scripts into a page. If anyone wants to sample this in their own browser, you can use the following JavaScript code:

```js
var trend = {};

function getChances() {
  trend = {
    random: {
      chance: 0,
      count: 0,
      min: 0,
      max: 0
    },
    down: {
      chance: 0,
      count: 0,
      min: 0,
      max: 0
    },
    small: {
      chance: 0,
      count: 0,
      min: 0,
      max: 0
    },
    large: {
      chance: 0,
      count: 0,
      min: 0,
      max: 0
    }
  }
  $('#output tr').each(function(){
    var type = $(this).children('td:nth-child(1)').text();
    var percent = parseFloat($(this).children('td:nth-child(2)').text());
    var low = parseInt($(this).children('td:nth-child(16)').text());
    var high = parseInt($(this).children('td:nth-child(17)').text());
    
    switch (type) {
      case 'Fluctuating':
        type = trend.random;
        break;
      case 'Decreasing':
        type = trend.down;
        break;
      case 'Small spike':
        type = trend.small;
        break;
      case 'Large spike':
        type = trend.large;
        break;
    }
    
    type.chance = percent;
    type.count++;
    type.min = low;
    type.max = high;
  });
  
  var totalCount = trend.large.count + trend.small.count + trend.random.count + trend.down.count;
  var randomChance = isNaN(trend.random.chance) ? `${((trend.random.count / totalCount) * 100).toFixed(0)}%` : `${(trend.random.chance * trend.random.count).toFixed(0)}%`;
  var downChance = isNaN(trend.down.chance) ? `${((trend.down.count / totalCount) * 100).toFixed(0)}%` : `${(trend.down.chance * trend.down.count).toFixed(0)}%`;
  var smallChance = isNaN(trend.small.chance) ? `${((trend.small.count / totalCount) * 100).toFixed(0)}%` : `${(trend.small.chance * trend.small.count).toFixed(0)}%`;
  var largeChance = isNaN(trend.large.chance) ? `${((trend.large.count / totalCount) * 100).toFixed(0)}%` : `${(trend.large.chance * trend.large.count).toFixed(0)}%`;
  
  $('.table-wrapper').before(`<div id="extraStats">
    <style>
      #extraStats, #extraStats>div {
        width: 100%;
        display: flex;
        justify-content: space-around;
      }
      #extraStats>div>div>* {
        text-align: center;
      }
      @media (max-width: 768px) {
        #extraStats {
          flex-direction: column;
        }
      }
    </style>
    <div>
      <div>
        <h2>Fluctuating</h2>
        <h3>Chance: ${randomChance}</h3>
        <h3>Min/Max: ${trend.random.min}~${trend.random.max}</h3>
      </div>
      <div>
        <h2>Decreasing</h2>
        <h3>Chance: ${downChance}</h3>
        <h3>Min/Max: ${trend.down.min}~${trend.down.max}</h3>
      </div>
    </div>
    <div>
      <div>
        <h2>Small Spike</h2>
        <h3>Chance: ${smallChance}</h3>
        <h3>Min/Max: ${trend.small.min}~${trend.small.max}</h3>
      </div>
      <div>
        <h2>Large Spike</h2>
        <h3>Chance: ${largeChance}</h3>
        <h3>Min/Max: ${trend.large.min}~${trend.large.max}</h3>
      </div>
    </div>
  </div>`);
}

getChances();

$('body').on('DOMSubtreeModified', '#output', function(){
  $('#extraStats').remove();
  getChances();
});
```
**Edit**: I have modified the above code to include other added suggestions discussed in this issue.

image

### PR DESCRIPTION
**Pull request by ChiefMilesEdgeworth**
[x] Added a column for the chance of a category
[x] Used rowspan to only have one entry for each category group
[x] Sorted output based on category chance

Let me know if you have anything that needs done

Closes #72, #65

### CODE REVIEW

**Comment by ChiefMilesEdgeworth** [comment]
I'm running into a small issue where I can't get the % col to show a newline, so that the two lines are separate for readability. If that can be fixed, this should look very good.

**Comment by ChiefMilesEdgeworth** [comment]
Nevermind, got it.

**Comment by mikebryant** [comment]
I like the idea of having the category, but I don't want to lose the individual row probabilities now they're actually different per option based on the Bayesian stuff.

I'm working on an extension to this that does both things

**Comment by mikebryant** [comment]
Thank you for your contirbution here :)

**Pull request closed without merging**
