### PR TITLE
Add support to remember prices in query string.

### PR DESCRIPTION
**Pull request by peter50216**
This makes linking to a particular price chart easier.

(I use "." as separator instead of "," so the URL looks a little nicer, URLSearchParams seems to escape "," to "%2C")

### CODE REVIEW

**Comment by mikebryant** [comment]
Thought - is there a danger here that someone clicks on a link from someone else, and therefore wipes their own data?

**Comment by theRTC204** [comment]
A query string seems more contextually appropriate for what you're doing here. The hash parameter should be used to point to a resource on a page, while the query string is meant to set values to parameters.

**Comment by peter50216** [comment]
Yeah currently it would override the data in localstorage, I'm not sure how many people actually use this site to record their own data. (I record mine on a spreadsheet elsewhere, so it's handy to have this so I can automatically generate a link to the prediction site :D)

**Comment by theRTC204** [comment]
One possible solution to @mikebryant's comment could be to not write to local storage if there is a URL segment present.

I would imagine that most people use the side to record their own data day to day throughout the week. Everyone that I know who uses it does it that way (and loves that it stores the values for them).

**Comment by peter50216** [comment]
One question is that this currently automatically changes the URL when there's input, so there would always be a URL segment present.

Or should I just not change the URL on input, and explicitly add a "share" button that would generate the URL for copy?

**Comment by peter50216** [comment]
Also if I change this to query string then it can't be automatically changed when input changes (writing to window.location.search reloads the page), but I guess this is not a problem if going for the route in the previous post.

**Comment by theRTC204** [comment]
> Also if I change this to query string then it can't be automatically changed when input changes (writing to window.location.search reloads the page), but I guess this is not a problem if going for the route in the previous post.

What you'd want to do is use the browser's History API to manipulate the history stack (https://developer.mozilla.org/en-US/docs/Web/API/History_API). This is the underlying native API that is used by frontend routers often paired with SPA frameworks like Angular or React.

A call to `history.replaceState()` should do the trick.

**Comment by theRTC204** [comment]
I'm curious, what is the intended value that this change brings? Given sell prices are largely randomized, and very personal to your island, what do you envision using the sharable URL for?

**Comment by peter50216** [comment]
> What you'd want to do is use the browser's History API to manipulate the history stack (https://developer.mozilla.org/en-US/docs/Web/API/History_API). This is the underlying native API that is used by frontend routers often paired with SPA frameworks like Angular or React.
> 
> A call to `history.replaceState()` should do the trick.

Oh yes I forgot about that, thanks for the hint!
Changed to query string.

**Comment by peter50216** [comment]
> I'm curious, what is the intended value that this change brings? Given sell prices are largely randomized, and very personal to your island, what do you envision using the sharable URL for?

The use case I have is that we have a group of friends playing ACNH, and a spreadsheet that everyone use to record their price and see others, so I want a quick link from the spreadsheet to the prediction site to see who got which pattern and still has a chance to have high price.

**Comment by theRTC204** [comment]
It's not my project, so really @mikebryant will have to weigh in his feelings. But my sense is adding a Share button that generates a link which pre-fills the fields seems fine, as long as the URL does not end up writing to Local Storage.

**Comment by peter50216** [comment]
Changed so that this "feature" is hidden from normal user at all, and you have to read the code to know there's a query string that can be used to pre-fill the form.

I feel that if we want to add a "share" button then we might need to have some banner showing that the view is somewhat readonly and you can go back to your save data by clicking some link. I'd leave that to another PR :smile:

**Comment by Trevor-Welch** [comment]
I would be willing to work on a PR for two different views based on URL params, and I would just add a param that is added to the URL from the Share button like ?source='share' or something like that that the page catches and prevents from writing to storage.

**Comment by mikebryant** [comment]
This is looking good, we can definitely add this and iterate :)

Thank you for working on this!

**Comment by Burry83** [comment]
Just bought this to life in a similar way @peter50216 as had a group of mates with a spreadsheet. When linking across thought the previous pattern data is lost and therefore my believe that the % Chance is not calculated. Is there any desire from anyone else to add the previous pattern onto the query string?

**Comment by Burry83** [comment]
I have so much time for this. Just set it all up from our google sheet and it has worked like a charm. Thank you all for this.

**Pull request merged**
